### PR TITLE
added mocked function to allow node-pixel mocking

### PR DESCRIPTION
**Pull request by FinKingma**
hey,

I added a new mock function that is required if you want to mock firmata with node-pixel.

regards,
Fin

### CODE REVIEW

**Comment by rwaldron** [comment]
Firmata.js's `Board` instances don't expose a `write` method.


Maybe @ajfisher can chime in?

**Comment by ajfisher** [comment]
I use Sinon for this because depending on what you are testing you may need to return different types of responses (eg different types of error) and I also use spies to look at things like call counts etc to make sure calls happen properly.

Node Pixel tests have been significantly updated over last couple of weeks so possibly the motivation that caused this PR may have disappeared.

**Comment by FinKingma** [comment]
When I update to a newer version of node-pixel I indeed no longer get this error. This PR is not needed apparently.

**Comment by ajfisher** [comment]
Great. Have done a lot of testing work recently so good to see this is no
longer a problem.

**Pull request closed without merging**
